const actionTypes = {
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  SHOW_CART: 'SHOW_CART',
  ADD_ITEM: 'ADD_ITEM',
  CLEAR_ITEM_FROM_CART: 'CLEAR_ITEM_FROM_CART',
  REMOVE_ITEM: 'REMOVE_ITEM'
}

export default actionTypes;
